displayName=Hide Minimap Hotkey
author=jarromie
description=Allows you to hide the minimap using a hotkey (resizable mode only; requires default Minimap plugin enabled)
tags=minimap,hotkey,toggle
plugins=com.jarromie.HideMinimapHotkeyPlugin